# Generated by Django 3.2.5 on 2021-08-20 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacsina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
                ('img', models.ImageField(upload_to='PasportImages/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('step1', models.BooleanField(default=False)),
                ('step2', models.BooleanField(default=False)),
                ('step3', models.BooleanField(blank=True, default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacsina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vacsina')),
            ],
        ),
    ]
